name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_HOST: ghcr.io
    steps:
      -
        name: üëØ‚Äç Checkout
        uses: actions/checkout@v3
      -
        name: ‚úÇÔ∏è Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=name;]$(echo ${GITHUB_REPOSITORY#*/})"
          echo "##[set-output name=ver;]$(echo ${GITHUB_REF#refs/*/})"
          echo "##[set-output name=minor_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*})"
          echo "##[set-output name=major_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*.*})"
          echo "##[set-output name=sha;]$(git rev-parse --short "$GITHUB_SHA")"
        id: extract_name_and_version
      -
        name: üñ• Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: ‚öôÔ∏è Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: üôãüèª‚Äç‚ôÇÔ∏è Login to ${{ env.REGISTRY_HOST }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: üî®Ôπ†üî∫ Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:latest"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.sha }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.major_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.ver }}"
          labels:
            "org.opencontainers.image.source=https://github.com/${{ github.repository }}"
          build-args: |
            SHORTENER_VERSION=${{ steps.extract_name_and_version.outputs.ver }}
          cache-from: type=registry,ref=${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}
          cache-to: type=inline
